### ISSUE TITLE
Your component is featured on my blog

### ISSUE THREAD

**Issue by binhbbui411** [BrightspaceUI/loading-spinner#27]
Hey there,  

Recently, I just published a piece featuring top 5 spinner web components and yours was a heck of a spinner.  
  
You have an outstanding component. Personally, I love the animation so much. If I build a web app, I would definitely use yours.
  
Here's the link to the blog [Top 5 spinners](https://vaadin.com/blog/5-spinner-web-components-for-your-site).  
  
It would be really cool if you give it some feedbacks/thoughts in the comment section.  
  
Regards,  
Binh

**Comment by dlockhart** [comment]
@binhbbui411 thanks so much for the feature in your piece. Glad you like it, and hopefully the apps you build are so fast that your users don't need to see it for too long! :)
